<?php

/**
 * Implements hook_menu
 */
function decathlon_edit_menu() {
  $items = array();

  $items['scores/game/%/edit'] = array(
    'title' => 'Edit Game',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('decathlon_edit_edit_form', 2),
    'access callback' => TRUE,
    'file' => 'decathlon_edit.inc',
    //    'file path' => drupal_get_path('module', 'decathlon'),
  );

  $items['scores/game/%/delete'] = array(
    'title' => 'Delete Game',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('decathlon_edit_delete_form', 2),
    'access callback' => TRUE,
    'file' => 'decathlon_edit.inc',
    //    'file path' => drupal_get_path('module', 'decathlon'),
  );

  return $items;
}
