<?php

/**
 * Register a content_types for ctools
 */
function decathlon_dpi_ctools_plugin_directory($owner, $plugin_type) {
  // we'll be nice and limit scandir() calls
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_views_api()
 */
function decathlon_dpi_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'decathlon_dpi'),
  );
} 



