<?php

/**
 * Register a content_types for ctools
 */
function decathlon_dpi_ctools_plugin_directory($owner, $plugin_type) {
  // we'll be nice and limit scandir() calls
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_views_api()
 */
function decathlon_dpi_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'decathlon_dpi'),
  );
} 

/**
 * Implements hook_theme()
 */
function decathlon_dpi_theme($existing, $type, $theme, $path) {
  return array(
    'decathlon_dpi_multipliers' => array(
      'render element' => 'element'
    ),
    'decathlon_dpi_weights' => array(
      'render element' => 'element'
    ),
    'decathlon_dpi_tiers' => array(
      'render element' => 'element'
    ),
  );
}




